apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sdp-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
