apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.app.name }}
 namespace: {{ .Values.namespace }}
 labels:
   app: {{ .Values.app.name }}
spec:
 replicas: {{ .Values.app.replicaCount }}
 selector:
  matchLabels:
   app: {{ .Values.app.name }}
 template:
  metadata:
   labels:
    app: {{ .Values.app.name }}
  spec:
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
    containers:
    - image: "{{ .Values.app.image.repository}}:{{ .Values.app.image.tag }}"
      name: {{ .Values.app.name }}
      imagePullPolicy: {{ .Values.app.pullPolicy }} 
      ports:
        - name: http
          containerPort: {{ .Values.app.service.port }}
    readinessProbe:
      tcpSocket:
        port: http
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: http
      initialDelaySeconds: 10
      periodSeconds: 20 
    env:
      - name: MONGODB_URL 
        valueFrom:
          secretKeyRef:
            name: mongodb-admin-app-rw-user
            key: connectionString.standardSrv 
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.app.name }}-svc
    namespace: {{ .Values.namespace }}
spec:
    ports:
    - name: {{ .Values.app.name }}-port
      targetPort: http
      port: {{ .Values.app.service.port }}
      protocol: TCP
    selector:
       app: {{ .Values.app.name }}
