---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  members: {{ .Values.database.replicaCount }}
  type: ReplicaSet
  version: {{ .Values.database.version }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.database.adminUsername }}
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: scram
    - name: {{ .Values.database.appUsername }}
      db: admin
      passwordSecretRef:
        name: app-rw-user-password
      roles:
        - name: readWrite
          db: admin
      scramCredentialsSecretName: app-rw-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

