## Values here might be overridden 
## by the configs in release-configs
namespace: sdp
database:
  replicaCount: 3
  version: "6.0.5"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

app:
  name: sdp-app
  replicaCount: 2

  image:
    repository: anoopvm/sdp-app
    pullPolicy: IfNotPresent
    tag: "v0.0.1"

  service:
    type: ClusterIP
    port: 3000

  certificateArn: ""

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}
