---
- name: Health check
  gather_facts: false
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: avm-test-bucket-12345

    services:
    - kubelet.service
    - containerd.service
    - ntpd.service      

  roles:
    - { role: health_check, services_list: "{{ services }}" }
